### ISSUE TITLE
Add support fo Lifx Switches

### ISSUE THREAD

**Issue by Narimm** [aiolifx/aiolifx#39]
Lifx has released a new product line - smart switchs the LAN protocol has been updated to support them 

https://lan.developer.lifx.com/docs/switch-messages

Each switch has 4 relays that can either be On or Off - switches dont support dimming.

**Comment by Narimm** [comment]
I have started making the changes here 
https://github.com/Narimm/aiolifx

**Comment by frawau** [comment]
OK.

Do not have one of those and the link to the doc is not working.

**Comment by Narimm** [comment]
https://lan.developer.lifx.com/v2.0 
So Lifx dont allow hotlinking to that page....god knows why..

**Comment by Narimm** [comment]
https://github.com/frawau/aiolifx/compare/master...Narimm:master 
I am not a python dev - java is my native tongue but I started work here

**Comment by Narimm** [comment]
I updated the original link.

**Comment by Djelibeybi** [comment]
Resolved via #67
